apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:openshift-authentication:hostaccess
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:hostaccess
subjects:
- kind: ServiceAccount
  namespace: openshift-authentication
  name: oauth-openshift
